# Generated by Django 4.1.7 on 2023-04-06 02:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('video', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mypothole',
            name='my_content',
        ),
        migrations.AlterField(
            model_name='mypothole',
            name='detect_file',
            field=models.FileField(upload_to='upload'),
        ),
        migrations.AlterField(
            model_name='mypothole',
            name='lat',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='mypothole',
            name='long',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='mypothole',
            name='title',
            field=models.CharField(default='20230406_115801_895044', max_length=200),
        ),
    ]
