# Generated by Django 4.1.7 on 2023-04-06 03:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('video', '0002_remove_mypothole_my_content_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mypothole',
            name='lat',
            field=models.CharField(blank=True, default=37.4765, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='mypothole',
            name='long',
            field=models.CharField(blank=True, default=126.9816, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='mypothole',
            name='title',
            field=models.CharField(default='20230406_120332_133546', max_length=200),
        ),
    ]
