# Generated by Django 4.1.7 on 2023-04-06 03:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('video', '0004_alter_mypothole_detect_file_alter_mypothole_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mypothole',
            name='title',
            field=models.CharField(default='20230406_123502_517725', max_length=200),
        ),
    ]
